-- Create a table for tracking lab access attempts
create table if not exists access_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  attempt_code text, -- The password they tried
  status text,       -- 'SUCCESS' or 'FAILURE'
  ip_address text,   -- Where they came from
  user_agent text    -- Browser info
);

-- Enable RLS (Security)
alter table access_logs enable row level security;

-- Policy: Allow the server (service role) to insert logs
-- Since we will use the API route with the service key/server client, this works.
-- But if we use the standard client in the API route, we need a policy.
-- Let's assume we want to allow anyone to insert (via the API route acting as a public endpoint)
-- but ONLY authenticated admins can read.

-- 1. Allow INSERT for everyone (public logging)
create policy "Allow public inserts" on access_logs for insert with check (true);

-- 2. Allow SELECT only for authenticated users (Admins)
create policy "Allow admin read" on access_logs for select using (auth.role() = 'authenticated');
