name: Uptime Ping

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Status Endpoint
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          curl -i -H "Authorization: Bearer $CRON_SECRET" https://reshinrajesh.in/api/cron/check-status
